# Generated by Django 3.2.9 on 2021-12-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': '1. Категории',
            },
        ),
        migrations.CreateModel(
            name='Complect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Название')),
                ('items_count', models.IntegerField(null=True, verbose_name='Обязательное кол-во товаров')),
                ('is_unlimited', models.BooleanField(default=False, verbose_name='Без ограничений по количеству')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': '3. Комплекты',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner', verbose_name='Баннер')),
                ('items_added', models.IntegerField(blank=True, default=0, editable=False, verbose_name='Кол-во товаров')),
                ('weigth', models.CharField(blank=True, max_length=10, null=True, verbose_name='Вес')),
                ('calories', models.CharField(blank=True, max_length=10, null=True, verbose_name='Калории')),
                ('is_selected', models.BooleanField(default=False, editable=False)),
                ('price', models.IntegerField(default=300, verbose_name='Цена')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='data.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': '2. Товары',
            },
        ),
    ]
