# Generated by Django 3.2.9 on 2021-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complect',
            options={'verbose_name': 'Рацион', 'verbose_name_plural': '3. Рационы'},
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='items', verbose_name='Изображение товара'),
        ),
    ]
