# Generated by Django 3.2.9 on 2021-12-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='items_added',
            field=models.IntegerField(blank=True, default=1, editable=False, verbose_name='Кол-во товаров'),
        ),
    ]
