# Generated by Django 3.2.9 on 2021-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211214_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='must_check_one_item',
            field=models.BooleanField(default=False, verbose_name='Должно быть выбрано 1 блюдо из этой категории'),
        ),
    ]
