# Generated by Django 3.2.9 on 2021-12-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20211205_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': '1. Категории'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': '2. Товары'},
        ),
        migrations.AlterModelOptions(
            name='menutype',
            options={'verbose_name': 'Тип меню', 'verbose_name_plural': '3. Типы меню'},
        ),
        migrations.AlterField(
            model_name='item',
            name='items_added',
            field=models.IntegerField(blank=True, default=0, editable=False, verbose_name='Кол-во товаров'),
        ),
    ]
