# Generated by Django 3.2.9 on 2021-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20211206_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='calories',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='item',
            name='weigth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Вес'),
        ),
    ]
