# Generated by Django 3.2.9 on 2021-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_complect_show_items_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='items', verbose_name='Изображение товара'),
        ),
    ]
