# Generated by Django 3.2.9 on 2021-12-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ostatok',
            field=models.IntegerField(default=0, verbose_name='Остаток'),
        ),
    ]
