# Generated by Django 3.2.9 on 2021-12-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcomplect',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartcomplectitem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
