# Generated by Django 3.2.9 on 2021-12-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '1. Пользователи'},
        ),
    ]
