# Generated by Django 3.2.9 on 2021-12-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211216_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcomplect',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
