# Generated by Django 3.2.9 on 2021-12-17 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20211216_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items_count',
            field=models.IntegerField(default=0),
        ),
    ]
