# Generated by Django 3.2.9 on 2021-12-14 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('fio', models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Эл. почта')),
                ('own_ref_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Собственный реф код')),
                ('used_ref_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Использованный реф код')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Баланс')),
                ('ref_bonuses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Реф бонусы')),
                ('total_spend', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Всего потрачено')),
                ('is_company', models.BooleanField(default=False, verbose_name='Это юр. лицо')),
                ('is_default_reffer', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('company_inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('company_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': '1. Пользователи',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название способа оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='UserRefferalThirdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Третья линия',
                'verbose_name_plural': '4. Третие линии',
            },
        ),
        migrations.CreateModel(
            name='UserRefferalSecondLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Вторая линия',
                'verbose_name_plural': '3. Вторые линии',
            },
        ),
        migrations.CreateModel(
            name='UserRefferalFirstLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Первая линия',
                'verbose_name_plural': '2. Первые линии',
            },
        ),
    ]
