# Generated by Django 3.2.9 on 2022-02-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ref_bonuses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Реф бонусы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_spend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, verbose_name='Всего потрачено'),
        ),
    ]
