# Generated by Django 3.2.9 on 2021-12-06 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название способа оплаты')),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': '1. Пользователи'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_summ',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='ref_bonuses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Реф бонусы'),
        ),
        migrations.CreateModel(
            name='UserRefferalThirdLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Третья линия',
                'verbose_name_plural': '4. Третие линии',
            },
        ),
        migrations.CreateModel(
            name='UserRefferalSecondLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Вторая линия',
                'verbose_name_plural': '3. Вторые линии',
            },
        ),
        migrations.CreateModel(
            name='UserRefferalFirstLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_line_refferals', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Рефералы')),
            ],
            options={
                'verbose_name': 'Первая линия',
                'verbose_name_plural': '2. Первые линии',
            },
        ),
    ]
