# Generated by Django 3.2.9 on 2021-12-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211206_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_kpp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП'),
        ),
    ]
