# Generated by Django 3.2.9 on 2021-12-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_company_kpp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_default_reffer',
            field=models.BooleanField(default=False, verbose_name='По умолчанию'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
    ]
