# Generated by Django 3.2.9 on 2021-12-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20211210_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ref_bonuses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Реф бонусы'),
        ),
    ]
