# Generated by Django 3.2.9 on 2021-12-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20211210_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_spend',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, verbose_name='Всего потрачено'),
        ),
    ]
