# Generated by Django 3.2.9 on 2021-12-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код заказа')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании')),
                ('company_address', models.TextField(blank=True, null=True, verbose_name='Юридический адрес')),
                ('company_inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=20, null=True, verbose_name='КПП')),
                ('company_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Контактное лицо')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('is_pay', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.item', verbose_name='Товар в заказе')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
        ),
    ]
