# Generated by Django 3.2.9 on 2021-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211206_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код заказа'),
        ),
    ]
