# Generated by Django 3.2.9 on 2021-12-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость доставки'),
        ),
    ]
