# Generated by Django 3.2.9 on 2021-12-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_delivery_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время доставки'),
        ),
    ]
