# Generated by Django 3.2.9 on 2021-12-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='Обработан'),
        ),
    ]
