# Generated by Django 3.2.9 on 2021-12-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_items_count',
            field=models.IntegerField(default=0),
        ),
    ]
