# Generated by Django 3.2.9 on 2021-12-27 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20211227_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.ordercity', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='ordercitysector',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='order.ordercity', verbose_name='Город'),
        ),
    ]
